[package]
name = "laps"
version = "0.1.0"
edition = "2024"
description = "Desktop application for the Laps timing system"

[dependencies]
bytemuck = { version = "1.21", features = ["extern_crate_alloc"] }
clap = { version = "4.5", features = ["derive"] }
resvg = "0.44"
crossbeam-channel = "0.5"
eframe = "0.29"
egui = "0.29"
log = "0.4"
simplelog = "0.12.2"
time = { version = "0.3", features = ["macros"] }
yuv = "0.8.14"

[target.'cfg(target_os = "macos")'.dependencies]
nokhwa = { version = "0.10.10", default-features = false, features = ["input-avfoundation"] }

[target.'cfg(target_os = "linux")'.dependencies]
nokhwa = { version = "0.10.10", default-features = false, features = ["input-v4l"] }

[target.'cfg(target_os = "windows")'.dependencies]
nokhwa = { version = "0.10.10", default-features = false, features = ["input-msmf"] }

[profile.dev.package.yuv]
opt-level = 2

[package.metadata.bundle]
name = "Laps"
identifier = "ru.fpvladder.laps"
icon = ["packaging/osx/icon.icns"]
osx_minimum_system_version = "10.15"
osx_info_plist_exts = ["packaging/osx/Info.plist.ext"]
