// Code generated by gioui.org/cmd/svg2gio; DO NOT EDIT.

package assets

import "image/color"
import "math"
import "gioui.org/op"
import "gioui.org/op/clip"
import "gioui.org/op/paint"
import "gioui.org/f32"

var ops op.Ops

func argb(c uint32) color.NRGBA {
	return color.NRGBA{A: uint8(c >> 24), R: uint8(c >> 16), G: uint8(c >> 8), B: uint8(c)}
}

func rect(p *clip.Path, origin, size f32.Point) {
	p.MoveTo(origin)
	p.LineTo(origin.Add(f32.Pt(size.X, 0)))
	p.LineTo(origin.Add(size))
	p.LineTo(origin.Add(f32.Pt(0, size.Y)))
	p.Close()
}

func ellipse(p *clip.Path, center, radius f32.Point) {
	r := radius.X
	// We'll model the ellipse as a circle scaled in the Y
	// direction.
	scale := radius.Y / r

	// https://pomax.github.io/bezierinfo/#circles_cubic.
	const q = 4 * (math.Sqrt2 - 1) / 3

	curve := r * q
	top := f32.Point{X: center.X, Y: center.Y - r*scale}

	p.MoveTo(top)
	p.CubeTo(
		f32.Point{X: center.X + curve, Y: center.Y - r*scale},
		f32.Point{X: center.X + r, Y: center.Y - curve*scale},
		f32.Point{X: center.X + r, Y: center.Y},
	)
	p.CubeTo(
		f32.Point{X: center.X + r, Y: center.Y + curve*scale},
		f32.Point{X: center.X + curve, Y: center.Y + r*scale},
		f32.Point{X: center.X, Y: center.Y + r*scale},
	)
	p.CubeTo(
		f32.Point{X: center.X - curve, Y: center.Y + r*scale},
		f32.Point{X: center.X - r, Y: center.Y + curve*scale},
		f32.Point{X: center.X - r, Y: center.Y},
	)
	p.CubeTo(
		f32.Point{X: center.X - r, Y: center.Y - curve*scale},
		f32.Point{X: center.X - curve, Y: center.Y - r*scale},
		top,
	)
}

var Image_testcard_fixed struct {
	ViewBox struct{ Min, Max f32.Point }
	Call    op.CallOp
}

func init() {
	m := op.Record(&ops)
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(0, 0))
		p.LineTo(f32.Pt(672, 0))
		p.LineTo(f32.Pt(672, 504))
		p.LineTo(f32.Pt(0, 504))
		p.LineTo(f32.Pt(0, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff131313), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(0, 0))
		p.LineTo(f32.Pt(96, 0))
		p.LineTo(f32.Pt(96, 336))
		p.LineTo(f32.Pt(0, 336))
		p.LineTo(f32.Pt(0, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc0c0c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(96, 0))
		p.LineTo(f32.Pt(96, 336))
		p.LineTo(f32.Pt(192, 336))
		p.LineTo(f32.Pt(192, 0))
		p.LineTo(f32.Pt(96, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc0c000), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(192, 0))
		p.LineTo(f32.Pt(192, 336))
		p.LineTo(f32.Pt(288, 336))
		p.LineTo(f32.Pt(288, 0))
		p.LineTo(f32.Pt(192, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff00c0c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(288, 0))
		p.LineTo(f32.Pt(288, 336))
		p.LineTo(f32.Pt(384, 336))
		p.LineTo(f32.Pt(384, 0))
		p.LineTo(f32.Pt(288, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff00c000), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(384, 0))
		p.LineTo(f32.Pt(384, 336))
		p.LineTo(f32.Pt(480, 336))
		p.LineTo(f32.Pt(480, 0))
		p.LineTo(f32.Pt(384, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc000c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(480, 0))
		p.LineTo(f32.Pt(480, 336))
		p.LineTo(f32.Pt(576, 336))
		p.LineTo(f32.Pt(576, 0))
		p.LineTo(f32.Pt(480, 0))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc00000), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(576, 0))
		p.LineTo(f32.Pt(576, 336))
		p.LineTo(f32.Pt(672, 336))
		p.LineTo(f32.Pt(672, 0))
		p.LineTo(f32.Pt(576, 0))
		p.MoveTo(f32.Pt(0, 336))
		p.LineTo(f32.Pt(96, 336))
		p.LineTo(f32.Pt(96, 378))
		p.LineTo(f32.Pt(0, 378))
		p.LineTo(f32.Pt(0, 336))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff0000c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(192, 336))
		p.LineTo(f32.Pt(288, 336))
		p.LineTo(f32.Pt(288, 378))
		p.LineTo(f32.Pt(192, 378))
		p.LineTo(f32.Pt(192, 336))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc000c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(384, 336))
		p.LineTo(f32.Pt(480, 336))
		p.LineTo(f32.Pt(480, 378))
		p.LineTo(f32.Pt(384, 378))
		p.LineTo(f32.Pt(384, 336))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff00c0c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(576, 336))
		p.LineTo(f32.Pt(672, 336))
		p.LineTo(f32.Pt(672, 378))
		p.LineTo(f32.Pt(576, 378))
		p.LineTo(f32.Pt(576, 336))
		spec := p.End()
		paint.FillShape(&ops, argb(0xffc0c0c0), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(0, 378))
		p.LineTo(f32.Pt(120, 378))
		p.LineTo(f32.Pt(120, 504))
		p.LineTo(f32.Pt(0, 504))
		p.LineTo(f32.Pt(0, 378))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff00214c), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(120, 378))
		p.LineTo(f32.Pt(240, 378))
		p.LineTo(f32.Pt(240, 504))
		p.LineTo(f32.Pt(120, 504))
		p.LineTo(f32.Pt(120, 378))
		spec := p.End()
		paint.FillShape(&ops, argb(0x00000fff), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(240, 378))
		p.LineTo(f32.Pt(360, 378))
		p.LineTo(f32.Pt(360, 504))
		p.LineTo(f32.Pt(240, 504))
		p.LineTo(f32.Pt(240, 378))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff32006a), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(480, 378))
		p.LineTo(f32.Pt(512, 378))
		p.LineTo(f32.Pt(512, 504))
		p.LineTo(f32.Pt(480, 504))
		p.LineTo(f32.Pt(480, 378))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff090909), clip.Outline{Path: spec}.Op())
	}
	{
		var p clip.Path
		p.Begin(&ops)
		p.MoveTo(f32.Pt(544, 378))
		p.LineTo(f32.Pt(576, 378))
		p.LineTo(f32.Pt(576, 504))
		p.LineTo(f32.Pt(544, 504))
		p.LineTo(f32.Pt(544, 378))
		spec := p.End()
		paint.FillShape(&ops, argb(0xff1d1d1d), clip.Outline{Path: spec}.Op())
	}
	Image_testcard_fixed.Call = m.Stop()
}
