[package]
name = "sensor-rssi-rp2040"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sensor-rssi-rp2040"
test = false
bench = false

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7", default-features = false }
embedded-hal = "1.0"
panic-halt = "1.0"
pio = "0.3"
rp2040-hal = "0.12"
rp2040-boot2 = "0.3"
