//! Native V4L2 backend over raw ioctls: videodev2 structs declared by
//! hand (repr(C)), typed ioctl wrappers generated by nix macros. No
//! -sys/bindgen/cc — cross-compiles with plain rustc.
//!
//! Enumeration never changes device state (ENUM_* ioctls only, no
//! S_FMT): switching a device into another mode before the real open
//! can leave the following stream in a throttled state.

use super::capture::{Capture, CaptureFormat, CaptureSession, DeviceInfo, Frame, FrameData, FrameError};
use super::Error;
use crate::config::camera::{CameraConfig, PixelConfig};
use std::ffi::CString;
use std::io;
use std::os::unix::io::RawFd;
use std::time::{Duration, Instant};

pub struct V4l2Capture;

pub struct V4l2Session {
    fd: RawFd,
    buffers: Vec<MmapBuffer>,
    negotiated: CaptureFormat,
    /// First frame validated at open: a valid first buffer is kept here
    /// instead of being drained.
    pending: Option<Frame>,
    /// (CLOCK_MONOTONIC, Instant) pair to convert driver timestamps.
    mono_anchor: (libc::timespec, Instant),
}

struct MmapBuffer {
    ptr: *mut u8,
    len: usize,
}

impl Drop for MmapBuffer {
    fn drop(&mut self) {
        unsafe {
            libc::munmap(self.ptr as *mut _, self.len);
        }
    }
}

// Sound: the session (fd + all mappings) moves wholesale to the capture
// thread and is used from there only — no sharing between threads.
unsafe impl Send for MmapBuffer {}

// ---------------------------------------------------------------------------
// ABI (linux/videodev2.h). Sizes and padding are part of the kernel ABI
// (v4l2_buffer is 88 bytes on 64-bit due to timeval/m alignment) —
// repr(C) reproduces them as long as the definitions below match the
// header byte for byte.
// ---------------------------------------------------------------------------

const V4L2_CAP_VIDEO_CAPTURE: u32 = 0x0000_0001;
const V4L2_BUF_TYPE_VIDEO_CAPTURE: u32 = 1;
const V4L2_MEMORY_MMAP: u32 = 1;
const V4L2_FIELD_NONE: u32 = 1;
/// Driver-flagged corrupted buffer (e.g. a USB packet lost mid-frame).
const V4L2_BUF_FLAG_ERROR: u32 = 0x40;
/// ENUM_* type tags — union branches are only read after these checks.
const V4L2_FRMSIZE_TYPE_DISCRETE: u32 = 1;
const V4L2_FRMIVAL_TYPE_DISCRETE: u32 = 1;
/// Timestamp source mask and the CLOCK_MONOTONIC value (kernel fills
/// `timestamp` in the source clock it announces via these flags).
const V4L2_BUF_FLAG_TIMESTAMP_MASK: u32 = 0x0000_e000;
const V4L2_BUF_FLAG_TIMESTAMP_MONOTONIC: u32 = 0x0000_2000;

const CAPTURE: u32 = V4L2_BUF_TYPE_VIDEO_CAPTURE;

#[repr(C)]
struct Capability {
    driver: [u8; 16],
    card: [u8; 32],
    bus_info: [u8; 32],
    version: u32,
    capabilities: u32,
    device_caps: u32,
    reserved: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Fract {
    numerator: u32,
    denominator: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
struct PixFormat {
    width: u32,
    height: u32,
    pixelformat: u32,
    field: u32,
    bytesperline: u32,
    sizeimage: u32,
    colorspace: u32,
    priv_: u32,
    flags: u32,
    ycbcr_enc_or_hsv_enc: u32,
    quantization: u32,
    xfer_func: u32,
}

#[repr(C)]
union FmtUnion {
    pix: PixFormat,
    _align: u64,
    _raw: [u8; 200],
}

#[repr(C)]
struct Format {
    typ: u32,
    fmt: FmtUnion,
}

#[repr(C)]
struct RequestBuffers {
    count: u32,
    typ: u32,
    memory: u32,
    capabilities: u32,
    flags: u8,
    reserved: [u8; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Timeval {
    sec: i64,
    usec: i64,
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Timecode {
    _raw: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
union BufMem {
    offset: u32,
    userptr: u64,
    planes: usize,
    fd: i32,
}

#[repr(C)]
struct Buffer {
    index: u32,
    typ: u32,
    bytesused: u32,
    flags: u32,
    field: u32,
    timestamp: Timeval,
    timecode: Timecode,
    sequence: u32,
    memory: u32,
    m: BufMem,
    length: u32,
    reserved2: u32,
    reserved: u32,
}

impl Buffer {
    fn new() -> Self {
        Buffer {
            index: 0,
            typ: CAPTURE,
            bytesused: 0,
            flags: 0,
            field: 0,
            timestamp: Timeval { sec: 0, usec: 0 },
            timecode: Timecode { _raw: [0; 4] },
            sequence: 0,
            memory: V4L2_MEMORY_MMAP,
            m: BufMem { offset: 0 },
            length: 0,
            reserved2: 0,
            reserved: 0,
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
struct CaptureParm {
    capability: u32,
    capturemode: u32,
    timeperframe: Fract,
    extendedmode: u32,
    readbuffers: u32,
    reserved: [u32; 4],
}

#[repr(C)]
union ParmUnion {
    capture: CaptureParm,
    _raw: [u8; 200],
}

#[repr(C)]
struct StreamParm {
    typ: u32,
    parm: ParmUnion,
}

#[repr(C)]
struct FmtDesc {
    index: u32,
    typ: u32,
    flags: u32,
    description: [u8; 32],
    pixelformat: u32,
    mbus_code: u32,
    reserved: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct DiscreteSize {
    width: u32,
    height: u32,
}

#[repr(C)]
union SizeUnion {
    discrete: DiscreteSize,
    _raw: [u32; 6],
}

#[repr(C)]
struct FrameSizeEnum {
    index: u32,
    pixel_format: u32,
    typ: u32,
    size: SizeUnion,
    reserved: [u32; 2],
}

#[repr(C)]
union IntervalUnion {
    discrete: Fract,
    _raw: [u32; 6],
}

#[repr(C)]
struct FrameIntervalEnum {
    index: u32,
    pixel_format: u32,
    width: u32,
    height: u32,
    typ: u32,
    interval: IntervalUnion,
    reserved: [u32; 2],
}

// Compile-time ABI checks against linux/videodev2.h: sizes catch padding
// surprises, offsets catch field reordering. Verified against the system
// header; if a struct below is ever edited, these numbers are the spec.
const _: () = {
    use std::mem::{offset_of, size_of};
    assert!(size_of::<Capability>() == 104);
    assert!(size_of::<Format>() == 208);
    assert!(size_of::<RequestBuffers>() == 20);
    assert!(size_of::<Buffer>() == 88);
    assert!(size_of::<StreamParm>() == 204);
    assert!(size_of::<FmtDesc>() == 64);
    assert!(size_of::<FrameSizeEnum>() == 44);
    assert!(size_of::<FrameIntervalEnum>() == 52);

    assert!(offset_of!(Capability, device_caps) == 88);
    assert!(offset_of!(Buffer, timestamp) == 24);
    assert!(offset_of!(Buffer, m) == 64);
    assert!(offset_of!(Buffer, length) == 72);
    assert!(offset_of!(Format, fmt) == 8);
    assert!(offset_of!(RequestBuffers, flags) == 16);
};

// Typed ioctl wrappers: request numbers and pointer casts come from nix
// macros (size_of the Rust struct goes into the request number).
nix::ioctl_read!(querycap, b'V', 0, Capability);
nix::ioctl_readwrite!(enum_fmt, b'V', 2, FmtDesc);
nix::ioctl_readwrite!(s_fmt, b'V', 5, Format);
nix::ioctl_readwrite!(reqbufs, b'V', 8, RequestBuffers);
nix::ioctl_readwrite!(querybuf, b'V', 9, Buffer);
nix::ioctl_readwrite!(qbuf, b'V', 15, Buffer);
nix::ioctl_readwrite!(dqbuf, b'V', 17, Buffer);
nix::ioctl_write_ptr!(streamon, b'V', 18, u32);
nix::ioctl_write_ptr!(streamoff, b'V', 19, u32);
nix::ioctl_readwrite!(s_parm, b'V', 22, StreamParm);
nix::ioctl_readwrite!(enum_framesizes, b'V', 74, FrameSizeEnum);
nix::ioctl_readwrite!(enum_frameintervals, b'V', 75, FrameIntervalEnum);

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

fn cstr(buf: &[u8]) -> String {
    let end = buf.iter().position(|&b| b == 0).unwrap_or(buf.len());
    String::from_utf8_lossy(&buf[..end]).into_owned()
}

fn fourcc(config: PixelConfig) -> u32 {
    match config {
        // b"MJPG" little-endian
        PixelConfig::Mjpeg => u32::from_le_bytes(*b"MJPG"),
        PixelConfig::Yuyv => u32::from_le_bytes(*b"YUYV"),
    }
}

fn pixel_config(fourcc: u32) -> Option<PixelConfig> {
    match &fourcc.to_le_bytes() {
        b"MJPG" => Some(PixelConfig::Mjpeg),
        b"YUYV" => Some(PixelConfig::Yuyv),
        _ => None,
    }
}

/// One frame is exactly SOI..EOI; FF is escaped as FF00 in entropy data,
/// so the first FFD9 after SOI is EOI. `None` — no EOI (buffer kept
/// whole, see FrameData::Jpeg).
fn jpeg_len(buf: &[u8]) -> Option<usize> {
    let start = if buf.starts_with(&[0xFF, 0xD8]) {
        0
    } else {
        buf.windows(2).position(|w| w == [0xFF, 0xD8])?
    };
    Some(memchr::memmem::find(&buf[start..], b"\xff\xd9")? + start + 2)
}

/// Enumerated capture node: path, card name, formats. Internal to
/// open() — DeviceInfo for the CLI carries no path.
struct Device {
    path: String,
    name: String,
    formats: Vec<CaptureFormat>,
}

fn open_node(path: &str) -> io::Result<RawFd> {
    let cpath = CString::new(path).unwrap();
    let fd = unsafe {
        libc::open(
            cpath.as_ptr(),
            libc::O_RDWR | libc::O_NONBLOCK | libc::O_CLOEXEC,
        )
    };
    if fd == -1 {
        Err(io::Error::last_os_error())
    } else {
        Ok(fd)
    }
}

fn query_capture_caps(fd: RawFd) -> io::Result<Option<String>> {
    // Zeroed + assume_init: Capability is integers and byte arrays only,
    // any bit pattern is valid, and a successful QUERYCAP fully fills it.
    let mut cap = std::mem::MaybeUninit::<Capability>::zeroed();
    unsafe { querycap(fd, cap.as_mut_ptr()) }.map_err(io::Error::from)?;
    let cap = unsafe { cap.assume_init() };
    let caps = if cap.device_caps != 0 {
        cap.device_caps
    } else {
        cap.capabilities
    };
    if caps & V4L2_CAP_VIDEO_CAPTURE == 0 {
        // Skip metadata nodes and other non-capture devices.
        return Ok(None);
    }
    Ok(Some(cstr(&cap.card)))
}

/// ENUM_* ioctls iterate a struct's index field until the call fails
/// (enumeration exhausted). The increment step lives on the struct.
trait EnumStep {
    fn bump(&mut self);
}

fn enum_next<T: EnumStep>(
    fd: RawFd,
    op: unsafe fn(RawFd, *mut T) -> nix::Result<i32>,
    item: &mut T,
) -> io::Result<()> {
    unsafe { op(fd, item) }.map_err(io::Error::from)?;
    item.bump();
    Ok(())
}

impl EnumStep for FmtDesc {
    fn bump(&mut self) {
        self.index += 1;
    }
}

impl EnumStep for FrameSizeEnum {
    fn bump(&mut self) {
        self.index += 1;
    }
}

impl EnumStep for FrameIntervalEnum {
    fn bump(&mut self) {
        self.index += 1;
    }
}

fn enumerate_formats(fd: RawFd) -> io::Result<Vec<CaptureFormat>> {
    let mut out = Vec::new();
    let mut desc = FmtDesc {
        index: 0,
        typ: CAPTURE,
        flags: 0,
        description: [0; 32],
        pixelformat: 0,
        mbus_code: 0,
        reserved: [0; 3],
    };
    while enum_next(fd, enum_fmt, &mut desc).is_ok() {
        if let Some(config) = pixel_config(desc.pixelformat) {
            enumerate_sizes(fd, desc.pixelformat, config, &mut out)?;
        }
    }
    Ok(out)
}

fn enumerate_sizes(
    fd: RawFd,
    fourcc: u32,
    config: PixelConfig,
    out: &mut Vec<CaptureFormat>,
) -> io::Result<()> {
    let mut sizes = FrameSizeEnum {
        index: 0,
        pixel_format: fourcc,
        typ: 0,
        size: SizeUnion { _raw: [0; 6] },
        reserved: [0; 2],
    };
    while enum_next(fd, enum_framesizes, &mut sizes).is_ok() {
        // Only discrete sizes are listed — a stepwise range read through
        // the discrete branch would be garbage.
        if sizes.typ != V4L2_FRMSIZE_TYPE_DISCRETE {
            continue;
        }
        // SAFETY: typ checked above — the driver filled the discrete branch.
        let discrete = unsafe { sizes.size.discrete };
        enumerate_intervals(fd, fourcc, config, discrete.width, discrete.height, out)?;
    }
    Ok(())
}

fn enumerate_intervals(
    fd: RawFd,
    fourcc: u32,
    config: PixelConfig,
    width: u32,
    height: u32,
    out: &mut Vec<CaptureFormat>,
) -> io::Result<()> {
    let mut ival = FrameIntervalEnum {
        index: 0,
        pixel_format: fourcc,
        width,
        height,
        typ: 0,
        interval: IntervalUnion { _raw: [0; 6] },
        reserved: [0; 2],
    };
    while enum_next(fd, enum_frameintervals, &mut ival).is_ok() {
        // Only discrete intervals are listed (see sizes above).
        if ival.typ != V4L2_FRMIVAL_TYPE_DISCRETE {
            continue;
        }
        // SAFETY: typ checked above — the driver filled the discrete branch.
        let fract = unsafe { ival.interval.discrete };
        // fps = denominator / numerator; skip fractional rates.
        if fract.numerator != 0 && fract.denominator % fract.numerator == 0 {
            out.push(CaptureFormat {
                resolution: crate::config::camera::ResolutionConfig { width, height },
                frame_rate: crate::config::camera::FrameRateConfig(
                    fract.denominator / fract.numerator,
                ),
                format: config,
            });
        }
    }
    Ok(())
}

/// Enumerates capture nodes. QUERYCAP/ENUM_* only — device state is
/// left untouched (no S_FMT).
fn enumerate_devices() -> io::Result<Vec<Device>> {
    let mut devices = Vec::new();
    for i in 0..64 {
        let path = format!("/dev/video{i}");
        let Ok(fd) = open_node(&path) else {
            continue;
        };
        let result: io::Result<Option<Device>> = (|| {
            let Some(name) = query_capture_caps(fd)? else {
                return Ok(None);
            };
            let formats = enumerate_formats(fd)?;
            Ok(Some(Device {
                path: path.clone(),
                name,
                formats,
            }))
        })();
        unsafe {
            libc::close(fd);
        }
        match result {
            Ok(Some(device)) => devices.push(device),
            Ok(None) => {}
            Err(e) => log::debug!("skipping {path}: {e}"),
        }
    }
    Ok(devices)
}

// ---------------------------------------------------------------------------
// Capture / CaptureSession
// ---------------------------------------------------------------------------

impl Capture for V4l2Capture {
    type Session = V4l2Session;

    fn list_devices() -> std::result::Result<Vec<DeviceInfo>, Error> {
        let devices = enumerate_devices()?;
        Ok(devices
            .into_iter()
            .map(|d| DeviceInfo {
                name: d.name,
                formats: d.formats,
            })
            .collect())
    }

    fn open(config: &CameraConfig) -> std::result::Result<Self::Session, Error> {
        let devices = enumerate_devices()?;
        let needle = config.name.to_lowercase();
        // Exact name match preferred over contains (two passes) — same
        // semantics as CameraConfig::matches.
        let candidates = devices.iter().filter(|d| d.name == config.name).chain(
            devices
                .iter()
                .filter(|d| d.name.to_lowercase().contains(&needle)),
        );
        let mut last_err = Error::Config(format!("camera not found: {}", config.name));
        for device in candidates {
            match open_session(&device.path, config) {
                Ok(session) => return Ok(session),
                Err(e) => last_err = e.into(),
            }
        }
        Err(last_err)
    }
}

/// Pair CLOCK_MONOTONIC with Instant taken back-to-back; the two calls
/// are what makes driver timestamps convertible to `Instant`.
fn clock_anchor() -> (libc::timespec, Instant) {
    // Zeroed: assume_init below is defined even if the syscall returned
    // an error (it cannot with CLOCK_MONOTONIC, zeroed costs nothing).
    let mut ts = std::mem::MaybeUninit::<libc::timespec>::zeroed();
    // SAFETY: ts is valid writable memory for the syscall duration;
    // CLOCK_MONOTONIC cannot fail on Linux.
    unsafe { libc::clock_gettime(libc::CLOCK_MONOTONIC, ts.as_mut_ptr()) };
    // SAFETY: timespec is integers only — any bit pattern is valid.
    (unsafe { ts.assume_init() }, Instant::now())
}

fn mono_to_instant(anchor: &(libc::timespec, Instant), ts: &Timeval) -> Instant {
    let frame = Duration::new(ts.sec.max(0) as u64, (ts.usec.max(0) as u32) * 1000);
    let base = Duration::new(
        anchor.0.tv_sec.max(0) as u64,
        anchor.0.tv_nsec.max(0) as u32,
    );
    if frame >= base {
        anchor.1 + (frame - base)
    } else {
        anchor.1
    }
}

fn open_session(path: &str, config: &CameraConfig) -> io::Result<V4l2Session> {
    let fd = open_node(path).map_err(|e| io::Error::new(e.kind(), format!("{path}: {e}")))?;
    let result: io::Result<V4l2Session> = (|| {
        let format = fourcc(config.format);
        let mut fmt = Format {
            typ: CAPTURE,
            fmt: FmtUnion {
                pix: PixFormat {
                    width: config.resolution.width,
                    height: config.resolution.height,
                    pixelformat: format,
                    field: V4L2_FIELD_NONE,
                    bytesperline: 0,
                    sizeimage: 0,
                    colorspace: 0,
                    priv_: 0,
                    flags: 0,
                    ycbcr_enc_or_hsv_enc: 0,
                    quantization: 0,
                    xfer_func: 0,
                },
            },
        };
        unsafe { s_fmt(fd, &mut fmt) }.map_err(io::Error::from)?;
        // S_PARM sets the frame interval; some drivers reject it — not
        // fatal, fall back to the requested rate.
        let mut parm = StreamParm {
            typ: CAPTURE,
            parm: ParmUnion {
                capture: CaptureParm {
                    capability: 0,
                    capturemode: 0,
                    timeperframe: Fract {
                        numerator: 1,
                        denominator: config.frame_rate.0,
                    },
                    extendedmode: 0,
                    readbuffers: 0,
                    reserved: [0; 4],
                },
            },
        };
        let fps = match unsafe { s_parm(fd, &mut parm) }.map_err(io::Error::from) {
            Ok(_) => {
                // SAFETY: the driver filled the capture branch of the union.
                let fract = unsafe { parm.parm.capture.timeperframe };
                if fract.numerator != 0 && fract.denominator % fract.numerator == 0 {
                    fract.denominator / fract.numerator
                } else {
                    config.frame_rate.0
                }
            }
            Err(e) => {
                log::warn!("{path}: S_PARM failed ({e}), fps from config");
                config.frame_rate.0
            }
        };
        // SAFETY: S_FMT filled the pix branch of the union.
        let negotiated_pix = unsafe { fmt.fmt.pix };

        let mut req = RequestBuffers {
            count: 4,
            typ: CAPTURE,
            memory: V4L2_MEMORY_MMAP,
            capabilities: 0,
            flags: 0,
            reserved: [0; 3],
        };
        unsafe { reqbufs(fd, &mut req) }.map_err(io::Error::from)?;
        if req.count == 0 {
            return Err(io::Error::other("driver allocated zero buffers"));
        }
        let mut buffers = Vec::with_capacity(req.count as usize);
        for index in 0..req.count {
            let mut buf = Buffer::new();
            buf.index = index;
            unsafe { querybuf(fd, &mut buf) }.map_err(io::Error::from)?;
            let ptr = unsafe {
                libc::mmap(
                    std::ptr::null_mut(),
                    buf.length as usize,
                    libc::PROT_READ | libc::PROT_WRITE,
                    libc::MAP_SHARED,
                    fd,
                    // SAFETY: offset is the u32 mmap offset returned by the driver.
                    buf.m.offset as libc::off_t,
                )
            };
            if ptr == libc::MAP_FAILED {
                return Err(io::Error::last_os_error());
            }
            buffers.push(MmapBuffer {
                ptr: ptr as *mut u8,
                len: buf.length as usize,
            });
            unsafe { qbuf(fd, &mut buf) }.map_err(io::Error::from)?;
        }
        let stream_type = CAPTURE;
        unsafe { streamon(fd, &stream_type) }.map_err(io::Error::from)?;
        let mono_anchor = clock_anchor();
        // The first frame after STREAMON can be a fragment (the stream
        // starts mid-frame). Dequeue a single buffer and drop it unless
        // it carries a valid preamble — a valid first frame is kept and
        // handed out as the session's pending frame.
        let mut pending = None;
        let mut pfd = libc::pollfd {
            fd,
            events: libc::POLLIN,
            revents: 0,
        };
        if unsafe { libc::poll(&mut pfd, 1, 500) } > 0 {
            let mut first = Buffer::new();
            if unsafe { dqbuf(fd, &mut first) }
                .map_err(io::Error::from)
                .is_ok()
            {
                let index = first.index as usize;
                if index < buffers.len() {
                    let expected_yuyv = (negotiated_pix.width * negotiated_pix.height * 2) as usize;
                    let used = (first.bytesused as usize).min(buffers[index].len);
                    // SAFETY: same invariants as extract_frame — valid
                    // index, mapped for the session's lifetime, no
                    // concurrent mutation (buffer not re-queued yet).
                    let raw = unsafe { std::slice::from_raw_parts(buffers[index].ptr, used) };
                    let valid = first.flags & V4L2_BUF_FLAG_ERROR == 0
                        && match config.format {
                            PixelConfig::Mjpeg => raw.starts_with(&[0xFF, 0xD8]),
                            PixelConfig::Yuyv => used == expected_yuyv,
                        };
                    if valid {
                        pending =
                            extract_frame(&buffers, index, used, config.format).map(|data| Frame {
                                timestamp: Instant::now(),
                                data,
                            });
                    } else {
                        // Первый рубеж обороны: фрагмент ожидаем, info.
                        log::info!("first frame after STREAMON is a fragment, drained");
                    }
                }
                let _ = unsafe { qbuf(fd, &mut first) }.map_err(io::Error::from);
            }
        }
        Ok(V4l2Session {
            fd,
            buffers,
            pending,
            mono_anchor,
            negotiated: CaptureFormat {
                resolution: crate::config::camera::ResolutionConfig {
                    width: negotiated_pix.width,
                    height: negotiated_pix.height,
                },
                frame_rate: crate::config::camera::FrameRateConfig(fps),
                format: config.format,
            },
        })
    })();
    if result.is_err() {
        unsafe {
            libc::close(fd);
        }
    }
    result
}

impl CaptureSession for V4l2Session {
    fn negotiated(&self) -> CaptureFormat {
        self.negotiated
    }

    fn frame(&mut self) -> std::result::Result<Frame, FrameError> {
        if let Some(frame) = self.pending.take() {
            return Ok(frame);
        }
        let mut buf = Buffer::new();
        // Non-blocking fd: EAGAIN → poll and retry.
        let mut dequeued = false;
        for _ in 0..8 {
            match unsafe { dqbuf(self.fd, &mut buf) }.map_err(io::Error::from) {
                Ok(_) => {
                    dequeued = true;
                    break;
                }
                Err(e) if e.raw_os_error() == Some(libc::EAGAIN) => {
                    let mut pfd = libc::pollfd {
                        fd: self.fd,
                        events: libc::POLLIN,
                        revents: 0,
                    };
                    let rc = unsafe { libc::poll(&mut pfd, 1, 2000) };
                    if rc <= 0 {
                        return Err(frame_error(rc));
                    }
                }
                Err(e) => return Err(frame_error_e(e)),
            }
        }
        if !dequeued {
            return Err(FrameError::Recoverable(
                "DQBUF kept returning EAGAIN after polling".to_owned(),
            ));
        }
        if buf.flags & V4L2_BUF_FLAG_ERROR != 0 {
            // Corrupted in transit (e.g. lost USB packet) — uvcvideo
            // delivers it flagged and possibly truncated.
            return Err(FrameError::Recoverable(format!(
                "driver flagged buffer {} as erroneous (sequence {})",
                buf.index, buf.sequence
            )));
        }
        let index = buf.index as usize;
        if index >= self.buffers.len() {
            return Err(FrameError::Recoverable(format!(
                "DQBUF returned index {} out of {} buffers",
                buf.index,
                self.buffers.len()
            )));
        }
        let data = extract_frame(
            &self.buffers,
            index,
            buf.bytesused as usize,
            self.negotiated.format,
        )
        .expect("index checked above");
        // Buffer copied — return it to the driver before processing.
        unsafe { qbuf(self.fd, &mut buf) }
            .map_err(|e| FrameError::Recoverable(io::Error::from(e).to_string()))?;
        Ok(Frame {
            timestamp: buffer_timestamp(&buf, &self.mono_anchor),
            data,
        })
    }
}

/// Frame timestamp: the driver one (exposure side) when it is
/// CLOCK_MONOTONIC and actually filled, else the dequeue moment. Zero
/// timestamps happen in practice: uvcvideo leaves them unset when the
/// device provides no clock source.
fn buffer_timestamp(buf: &Buffer, anchor: &(libc::timespec, Instant)) -> Instant {
    let monotonic = buf.flags & V4L2_BUF_FLAG_TIMESTAMP_MASK == V4L2_BUF_FLAG_TIMESTAMP_MONOTONIC;
    if monotonic && (buf.timestamp.sec != 0 || buf.timestamp.usec != 0) {
        mono_to_instant(anchor, &buf.timestamp)
    } else {
        Instant::now()
    }
}

/// Copy a dequeued buffer into FrameData, trimming MJPEG to SOI..EOI.
/// `index` must be a valid buffer index (caller checks).
fn extract_frame(
    buffers: &[MmapBuffer],
    index: usize,
    used: usize,
    format: PixelConfig,
) -> Option<FrameData> {
    let buffer = buffers.get(index)?;
    let used = used.min(buffer.len);
    // SAFETY: ptr/len come from our own successful mmap and stay mapped
    // for the session's lifetime; the caller passes a valid index; the
    // buffer is not aliased mutably while we read (copy-out happens
    // before the buffer is re-queued to the driver).
    let raw = unsafe { std::slice::from_raw_parts(buffer.ptr, used) };
    Some(match format {
        PixelConfig::Mjpeg => {
            let mut buf = raw.to_vec();
            let len = match jpeg_len(&buf) {
                Some(len) => {
                    buf.truncate(len);
                    Some(len)
                }
                None => {
                    log::warn!("frame without EOI, buffer kept whole");
                    None
                }
            };
            FrameData::Jpeg { buf, len }
        }
        PixelConfig::Yuyv => FrameData::Yuyv { buf: raw.to_vec() },
    })
}

fn frame_error(poll_rc: i32) -> FrameError {
    if poll_rc == 0 {
        FrameError::Recoverable("DQBUF poll timeout".to_owned())
    } else {
        FrameError::Unrecoverable(format!("DQBUF poll error: {poll_rc}"))
    }
}

fn frame_error_e(e: io::Error) -> FrameError {
    match e.raw_os_error() {
        Some(libc::ENODEV) | Some(libc::EIO) => FrameError::Unrecoverable(e.to_string()),
        _ => FrameError::Recoverable(e.to_string()),
    }
}

impl Drop for V4l2Session {
    fn drop(&mut self) {
        let typ = CAPTURE;
        let _ = unsafe { streamoff(self.fd, &typ) };
        // Fields drop after this: MmapBuffer unmaps itself, then fd closes.
        drop(std::mem::take(&mut self.buffers));
        unsafe {
            libc::close(self.fd);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::jpeg_len;

    #[test]
    fn jpeg_len_finds_eoi() {
        let buf = [0xFF, 0xD8, 1, 2, 0xFF, 0x00, 3, 0xFF, 0xD9, 9, 9];
        assert_eq!(jpeg_len(&buf), Some(9));
        assert_eq!(jpeg_len(&buf[..8]), None);
        assert_eq!(jpeg_len(&[]), None);
    }
}
